[gcp_service_account]
type = "service_account"
project_id = "prismatic-grail-447013-n7"
private_key_id = "b987573a7ddda9941de5d8abf713ccdef2779643"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDReUYNKDFo8hUd
Gj1LFxPHnoxctZoOsSNm6uPeMfJ7xj06pRw3Y197M2qjQl8jh8Qu9TRyPHBPXAa3
C33rxjsGssmTKnf+vMT6kgDerNvjoJR/HGZXQU4bXL9iGBm59RMIqqYsIhmpPqns
G6uLH/h2gaSzMIJiY5UyI1kd3RpBAvGjUF40Z8iYHKz2CBKi22tLdPYks/gcmV+T
cN44kMdnG6fF9gA6/Vgi3WEDEnJhWubFUhjcej6VUjZzhdo4em90KbklCMCAzrKJ
t6yYY4rdhEGwwsZyC6biF73he4eStQxMlkFscONye0wF9JE6RdodBQQSZLVtEIsG
gVICc5Y1AgMBAAECggEAJokpbnU09coHQVXY7c3+iQwtZUbRYx+KVD4lEnTc15Fm
JTpHwRbKc3dHiGZG61noKP1aGyPsQ2U6JQV7slrC9B4DAExhS989W51thImHYE5j
0yiN2UJ91IHRAYJOhUvFJySBsn/Jeb258+I5Qjxs8Jw0CPUFH4WTZmhjVh+dW1US
m8giw/yfV97ePrRFfW8JRgBjj9PVY8QbXCl208aN9EdG4e+2WWbb6altzqzUN6qy
GoNhXJ4oRY7Z7sjrr+EdugQmppzvK9f/goNeKuINe/iBAN5rbfUUprMrJ8gsgSBo
cF7srNBUG7E+tuOj0SsSeFpnexSzlL0zqhZHYECRlwKBgQDooSjo7gme9gxLllJ5
KmW6TM6JWPmppQ2p6LNPhMoAess6LL15VsJh7bzsS6JP4F8lPIZsb7ziTGQ84o0s
+ZE8PDaLLzJgcvRj5KQEVglVLn++FTFD59G6Pi4gHHPjLIYchPLOAfQDsYzvrgyA
cNWuCu9EuS+JFlifsEDeChWFKwKBgQDmhJXhlWlQUgU1i/Lf9gBcr9bLETzFMPHk
exX+nkJMF3dQSAW9xEfCP8HniKMF1sHmZBrNY7yAvOzBD7oftVrUAV9GZ6gyffYY
G1E9pCNQTJc0jv/4Wxk+cktFhlz7zMYw6vlDtc1sqGNxhVPnyhEg8inLlv4vnCVA
fLea05piHwKBgQDRTwg3JM5lR69iZ1vHh31Gdgszi2n/2PGFWknUF3+FlPa8XjsR
LR3y7Oyak6b0RcZ2A5JTiOojl2ZtXc52lAq4btkIvKuQGn6ITtXAzQTSrubjScAt
AC01bPMlk1Q2J/53NKwe7aT3mc5cbXb0LhIk6dPFOvZpW0DcVcLXxaz9RwKBgAms
OpXSrS6fonRSwQhAzFcXUc4HlSM5II1T1OJwRZvnyCvoOcVyvQgboMlUZHLURiKi
xLUloD1OsCiRvl+iPoNy40qTAu3Ld04fp1MM1iaCcD3WWktTl0WVii8KqlAukYpv
8bGzqUEL99BFpfWt9vYI81QFq/jXdoC0OwgWJP5FAoGALMy9L0qF/faOIbLSxnqM
rmK422+3F1n1causRhXM/xH8ydY2nCvTx/7KzBPgHEPHiV3sT2wp//Xiu7Fd2tBV
YUD1dPIL+sWvwux8K5fM4HKnnuui8xMVYdVa1Xt1E8CBqznFOxAeFq32SnlFVaod
dBKfljkcGyqe8dVoP5XIUnE=
-----END PRIVATE KEY-----
"""
client_email = "conta-sheets@prismatic-grail-447013-n7.iam.gserviceaccount.com"
client_id = "102490709862510308880"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/conta-sheets%40prismatic-grail-447013-n7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
